# Generated by Django 3.1.3 on 2020-11-18 14:07

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import imagekit.models.fields
import tinymce.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GroupPerson',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('image', imagekit.models.fields.ProcessedImageField(upload_to='images/')),
                ('active', models.BooleanField(default=False)),
            ],
            options={
                'db_table': 'group_person',
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, editable=False, populate_from='full_name', unique_with=['full_name'])),
                ('education', tinymce.models.HTMLField()),
                ('projects', tinymce.models.HTMLField()),
                ('complaints', models.PositiveIntegerField(default=0)),
                ('sentences', models.PositiveIntegerField(default=0)),
                ('voted', models.IntegerField(choices=[(0, 'A Favor'), (1, 'Abstención')], default=0)),
                ('photo', imagekit.models.fields.ProcessedImageField(upload_to='images/')),
                ('linkedin', models.URLField()),
                ('informed_vote', models.URLField()),
                ('active', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('group_person', models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='group_person', to='political.groupperson')),
            ],
            options={
                'db_table': 'person',
            },
        ),
    ]
